# Generated by Django 4.0.1 on 2022-04-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petstagramuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
